### ISSUE TITLE
embedded mode document content get missed by tika

### ISSUE THREAD

**Issue by ziqizhang** [ziqizhang/jate#11] opened 2015-10-09 13:41 UTC
using the Indexing class to index documents, which uses Tika to parse text and take content. 

It seems sometimes Tika fails to parse the text and extract content properly. Example: try aclrd corpus with docid=the-acl-rd-tec_chunk_10228.txt

**Comment by jerrygaoLondon** [comment] 2015-10-13 21:30
@ziqizhang  I can reproduce the problem you have encountered with. The problem is exactly the same as you suspected which is caused by Tika AutoDetectParser. The AutoDetectParser failed to detect correct file type sometimes for particular file.

I'm not sure what is the best way to solve this problem. Adding additional metadata about the file can help Tika detect correct file type.
For example,
```
metadata.add(Metadata.RESOURCE_NAME_KEY, f.getName());
```
However, this is still not able to extract content from the three file that we've found the problem.

So...
The quick solution is to detect file additionally by Files.probeContentType(f.toPath()).

then we can instance a specific org.apache.tika.parser.Parser to process the file content. In current case, if "txt" is detected, parser should be instanced to be TXTParser().
That is :
```
parser = new TXTParser();
BodyContentHandler handler = new BodyContentHandler();
Metadata metadata = new Metadata();
metadata.add(Metadata.RESOURCE_NAME_KEY, f.getName());
InputStream inputstream = TikaInputStream.get(f);
ParseContext context = new ParseContext();
parser.parse(inputstream, handler, metadata, context);
System.out.println("File content : " + handler.toString());
```

Directly using the specific file parser works well.

A good reference of Tika file parser, access via http://www.tutorialspoint.com/tika/tika_content_extraction.htm

**Comment by jerrygaoLondon** [comment] 2015-10-15 18:12
Fixed now! A new ContentExtractor resolve the problem by wrapping Tika inside.

**Closed by jerrygaoLondon** 2015-10-15 18:12 UTC
